spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/cuentoskilla
    username: postgres
    password: 993753
    hikari:
      data-source-properties:
        prepareThreshold: 0       # evita problema con Supabase Pooler                
  jpa:
    hibernate:
      ddl-auto: validate
    show-sql: true
cors:
  allowed-origins:  
    - http://localhost:4200
    - https://cuentos-killa-fe.vercel.app
    - https://cuentos-killa-fe-ionvantes-projects.vercel.app
    - https://killacuentos.web.app/
  allowed-methods: GET,POST,PUT,DELETE,OPTIONS
  allowed-headers: "*"
  allow-credentials: true  

  mail:
    host: smtp.gmail.com
    port: 587
    username: ${SPRING_MAIL_USERNAME:}
    password: ${SPRING_MAIL_PASSWORD:}
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true

file:
  upload-dir: uploads/vouchers

upload:
  max-size: 5242880

storage:
  provider: local

firebase:
  credentials: ${FIREBASE_CREDENTIALS:firebase-adminsdk.json}
  bucket: ${FIREBASE_BUCKET:cuentoskillabe.firebasestorage.app}

mercadopago:
  access-token: YOUR_ACCESS_TOKEN # Existing
  back-urls:
    success: https://your-frontend.com/payment/success
    failure: https://your-frontend.com/payment/failure
    pending: https://your-frontend.com/payment/pending
  notification-url: https://your-api-backend.com/api/webhooks/mercadopago

jwt:
  secret: ${JWT_SECRET:4d3c57bd9dd50faac21b00810e6606c2fe256ba80be9c6f32556ca053a9f5796}

sentry:
  dsn: ${SENTRY_DSN:}
  send-default-pii: true
  logging:
    minimum-event-level: error
  
