spring:
  datasource:
    url: ${SPRING_DATASOURCE_URL}
    username: ${SPRING_DATASOURCE_USERNAME}
    password: ${SPRING_DATASOURCE_PASSWORD}
    hikari:
      data-source-properties:
        prepareThreshold: 0       # evita problema con Supabase Pooler    
  jpa:
    hibernate:
      ddl-auto: validate          # Use 'validate' to ensure schema matches, change to 'update' if needed
    show-sql: true

file:
  upload-dir: uploads/vouchers

firebase:
  credentials: ${FIREBASE_CREDENTIALS:firebase-adminsdk.json}
  bucket: ${FIREBASE_BUCKET:}

mercadopago:
  access-token: YOUR_ACCESS_TOKEN # Existing
  back-urls:
    success: https://your-frontend.com/payment/success
    failure: https://your-frontend.com/payment/failure
    pending: https://your-frontend.com/payment/pending
  notification-url: https://your-api-backend.com/api/webhooks/mercadopago
