spring:
  datasource:
    url: ${SPRING_DATASOURCE_URL}
    username: ${SPRING_DATASOURCE_USERNAME}
    password: ${SPRING_DATASOURCE_PASSWORD}
    hikari:
      data-source-properties:
        prepareThreshold: 0       # evita problema con Supabase Pooler        
  jpa:
    hibernate:
      ddl-auto: validate
    show-sql: true

file:
  upload-dir: ./uploads/vouchers

upload:
  max-size: 5242880

storage:
  provider: local

mercadopago:
  access-token: YOUR_ACCESS_TOKEN # Existing
  back-urls:
    success: https://your-frontend.com/payment/success
    failure: https://your-frontend.com/payment/failure
    pending: https://your-frontend.com/payment/pending
  notification-url: https://your-api-backend.com/api/webhooks/mercadopago

sentry:
  dsn: https://206c3de140ffe2f6be2200ed522250b1@o4509612268912640.ingest.us.sentry.io/4509612333727744
  send-default-pii: true
  logging:
    minimum-event-level: error
