spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/cuentoskilla
    username: postgres
    password: 993753
    driver-class-name: org.postgresql.Driver
    hikari:
      maximum-pool-size: 10
      minimum-idle: 5
      connection-timeout: 20000
      idle-timeout: 300000
      max-lifetime: 1200000
      auto-commit: true
      data-source-properties:
        prepareThreshold: 0
  jpa:
    hibernate:
      ddl-auto: validate
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        format_sql: true
        jdbc:
          fetch_size: 50
          batch_size: 10
        order_inserts: true
        order_updates: true
  flyway:
    enabled: true
    baseline-on-migrate: true
    locations: classpath:db/migration
    repair: true
    detect-encoding: true
  mail:
    host: smtp.gmail.com
    port: 587
    username: ${SPRING_MAIL_USERNAME:cuentoskilla@gmail.com}
    password: ${SPRING_MAIL_PASSWORD:nfug jaiv ythi jfbe}
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true

cors:
  allowed-origins:  
    - http://localhost:4200
    - https://cuentos-killa-fe.vercel.app
    - https://cuentos-killa-fe-ionvantes-projects.vercel.app
    - https://killacuentos.web.app/
  allowed-methods: GET,POST,PUT,DELETE,OPTIONS
  allowed-headers: "*"
  allow-credentials: true  

file:
  upload-dir: uploads/vouchers

boleta:
  upload-dir: uploads/boletas

upload:
  max-size: 5242880

storage:
  provider: local

firebase:
  credentials: ${FIREBASE_CREDENTIALS:firebase-service-account.json}
  bucket: ${FIREBASE_BUCKET:cuentoskilla-f84ff.firebasestorage.app}

mercadopago:
  access-token: YOUR_ACCESS_TOKEN # Existing
  back-urls:
    success: https://your-frontend.com/payment/success
    failure: https://your-frontend.com/payment/failure
    pending: https://your-frontend.com/payment/pending
  notification-url: https://your-api-backend.com/api/webhooks/mercadopago

jwt:
  secret: ${JWT_SECRET:4d3c57bd9dd50faac21b00810e6606c2fe256ba80be9c6f32556ca053a9f5796}

sentry:
  dsn: ${SENTRY_DSN:}
  send-default-pii: true
  logging:
    minimum-event-level: error
  
frontend:
  url: ${FRONTEND_URL:https://killacuentos.web.app}



