ALTER TABLE direcciones
ADD COLUMN IF NOT EXISTS tipo_direccion VARCHAR(30);

ALTER TABLE orders
ADD COLUMN IF NOT EXISTS direccion_id BIGINT,
ADD COLUMN IF NOT EXISTS direccion TEXT,
ADD COLUMN IF NOT EXISTS tipo_direccion VARCHAR(30),
ADD COLUMN IF NOT EXISTS departamento VARCHAR(255),
ADD COLUMN IF NOT EXISTS provincia VARCHAR(255),
ADD COLUMN IF NOT EXISTS distrito VARCHAR(255),
ADD COLUMN IF NOT EXISTS calle VARCHAR(255),
ADD COLUMN IF NOT EXISTS referencia VARCHAR(255),
ADD COLUMN IF NOT EXISTS codigo_postal VARCHAR(10);

CREATE INDEX IF NOT EXISTS idx_orders_direccion_id ON orders(direccion_id);
